# Generated by Django 5.2.7 on 2025-10-11 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VanlifeApi', '0002_host_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='user',
        ),
    ]
