name: Deploy Django Backend to Lambda

on:
  push:
    branches: [main]
    paths: ['backend/**']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        cd backend
        pip install -r requirements.txt
    
    - name: Create deployment package
      run: |
        cd backend/Vanlife
        pip install -r ../requirements.txt -t .
        zip -r ../../vanlife-lambda.zip . -x "*.pyc" "__pycache__/*" "*.git*" "db.sqlite3"
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Deploy Lambda function
      run: |
        aws lambda update-function-code \
          --function-name vanlife-api \
          --zip-file fileb://vanlife-lambda.zip
    
    - name: Update Lambda environment variables
      run: |
        aws lambda update-function-configuration \
          --function-name vanlife-api \
          --environment Variables="{
            DJANGO_SETTINGS_MODULE=Vanlife.settings,
            DB_NAME=${{ secrets.DB_NAME }},
            DB_USER=${{ secrets.DB_USER }},
            DB_PASSWORD=${{ secrets.DB_PASSWORD }},
            DB_HOST=${{ secrets.DB_HOST }},
            DB_PORT=${{ secrets.DB_PORT }}
          }"