name: Deploy Django with Zappa

on:
  push:
    branches: [master]
    paths: ['backend/**', '.github/workflows/deploy-zappa.yml']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Create virtual environment and install dependencies
      run: |
        cd backend/Vanlife
        python -m venv venv
        source venv/bin/activate
        pip install -r ../requirements.txt
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Deploy with Zappa
      run: |
        cd backend/Vanlife
        source venv/bin/activate
        export DB_NAME=${{ secrets.DB_NAME }}
        export DB_USER=${{ secrets.DB_USER }}
        export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
        export DB_HOST=${{ secrets.DB_HOST }}
        export DB_PORT=${{ secrets.DB_PORT }}
        zappa update production || zappa deploy production
    
    - name: Run Django migrations
      run: |
        cd backend/Vanlife
        source venv/bin/activate
        zappa manage production migrate
    
    - name: Create superuser
      run: |
        cd backend/Vanlife
        source venv/bin/activate
        echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('admin', '${{ secrets.ADMIN_EMAIL }}', '${{ secrets.ADMIN_PASSWORD }}') if not User.objects.filter(username='admin').exists() else print('Admin user already exists')" | zappa manage production shell